apiVersion: v1
kind: ConfigMap
metadata:
  name: task-scheduler-config
data:
  REDIS_URL: redis:6379
  ETCD_ENDPOINTS: etcd-0.etcd:2379,etcd-1.etcd:2379,etcd-2.etcd:2379
  REDIS_STREAM_NAME: jobs
  REDIS_GROUP_NAME: workers
  LOG_LEVEL: INFO
  LOG_FORMAT: JSON
