apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: taskuser
  POSTGRES_PASSWORD: taskpass
  POSTGRES_DB: taskdb
  POSTGRES_DSN: postgres://taskuser:taskpass@postgres:5432/taskdb?sslmode=disable
